/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssetsIndexRouteImport } from './routes/assets/index'
import { Route as AssetsSlugRouteImport } from './routes/assets/$slug'
import { Route as AssetsNewRouteImport } from './routes/assets/new'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as OnboardingExpensesRouteImport } from './routes/onboarding/expenses'
import { Route as OnboardingIncomeRouteImport } from './routes/onboarding/income'
import { Route as OnboardingPlanRouteImport } from './routes/onboarding/plan'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsExpensesRouteImport } from './routes/settings/expenses'
import { Route as SettingsIncomeRouteImport } from './routes/settings/income'
import { Route as SettingsRulesIndexRouteImport } from './routes/settings/rules/index'
import { Route as SettingsRulesIdRouteImport } from './routes/settings/rules/$id'
import { Route as SettingsRulesNewRouteImport } from './routes/settings/rules/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsIndexRoute = AssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsSlugRoute = AssetsSlugRouteImport.update({
  id: '/assets/$slug',
  path: '/assets/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsNewRoute = AssetsNewRouteImport.update({
  id: '/assets/new',
  path: '/assets/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingExpensesRoute = OnboardingExpensesRouteImport.update({
  id: '/onboarding/expenses',
  path: '/onboarding/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIncomeRoute = OnboardingIncomeRouteImport.update({
  id: '/onboarding/income',
  path: '/onboarding/income',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingPlanRoute = OnboardingPlanRouteImport.update({
  id: '/onboarding/plan',
  path: '/onboarding/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsExpensesRoute = SettingsExpensesRouteImport.update({
  id: '/settings/expenses',
  path: '/settings/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIncomeRoute = SettingsIncomeRouteImport.update({
  id: '/settings/income',
  path: '/settings/income',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRulesIndexRoute = SettingsRulesIndexRouteImport.update({
  id: '/settings/rules/',
  path: '/settings/rules/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRulesIdRoute = SettingsRulesIdRouteImport.update({
  id: '/settings/rules/$id',
  path: '/settings/rules/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRulesNewRoute = SettingsRulesNewRouteImport.update({
  id: '/settings/rules/new',
  path: '/settings/rules/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets/$slug': typeof AssetsSlugRoute
  '/assets/new': typeof AssetsNewRoute
  '/onboarding/expenses': typeof OnboardingExpensesRoute
  '/onboarding/income': typeof OnboardingIncomeRoute
  '/onboarding/plan': typeof OnboardingPlanRoute
  '/settings/expenses': typeof SettingsExpensesRoute
  '/settings/income': typeof SettingsIncomeRoute
  '/assets/': typeof AssetsIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/settings/rules/$id': typeof SettingsRulesIdRoute
  '/settings/rules/new': typeof SettingsRulesNewRoute
  '/settings/rules/': typeof SettingsRulesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets/$slug': typeof AssetsSlugRoute
  '/assets/new': typeof AssetsNewRoute
  '/onboarding/expenses': typeof OnboardingExpensesRoute
  '/onboarding/income': typeof OnboardingIncomeRoute
  '/onboarding/plan': typeof OnboardingPlanRoute
  '/settings/expenses': typeof SettingsExpensesRoute
  '/settings/income': typeof SettingsIncomeRoute
  '/assets': typeof AssetsIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/settings/rules/$id': typeof SettingsRulesIdRoute
  '/settings/rules/new': typeof SettingsRulesNewRoute
  '/settings/rules': typeof SettingsRulesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets/$slug': typeof AssetsSlugRoute
  '/assets/new': typeof AssetsNewRoute
  '/onboarding/expenses': typeof OnboardingExpensesRoute
  '/onboarding/income': typeof OnboardingIncomeRoute
  '/onboarding/plan': typeof OnboardingPlanRoute
  '/settings/expenses': typeof SettingsExpensesRoute
  '/settings/income': typeof SettingsIncomeRoute
  '/assets/': typeof AssetsIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/settings/rules/$id': typeof SettingsRulesIdRoute
  '/settings/rules/new': typeof SettingsRulesNewRoute
  '/settings/rules/': typeof SettingsRulesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets/$slug'
    | '/assets/new'
    | '/onboarding/expenses'
    | '/onboarding/income'
    | '/onboarding/plan'
    | '/settings/expenses'
    | '/settings/income'
    | '/assets/'
    | '/onboarding/'
    | '/settings/'
    | '/settings/rules/$id'
    | '/settings/rules/new'
    | '/settings/rules/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets/$slug'
    | '/assets/new'
    | '/onboarding/expenses'
    | '/onboarding/income'
    | '/onboarding/plan'
    | '/settings/expenses'
    | '/settings/income'
    | '/assets'
    | '/onboarding'
    | '/settings'
    | '/settings/rules/$id'
    | '/settings/rules/new'
    | '/settings/rules'
  id:
    | '__root__'
    | '/'
    | '/assets/$slug'
    | '/assets/new'
    | '/onboarding/expenses'
    | '/onboarding/income'
    | '/onboarding/plan'
    | '/settings/expenses'
    | '/settings/income'
    | '/assets/'
    | '/onboarding/'
    | '/settings/'
    | '/settings/rules/$id'
    | '/settings/rules/new'
    | '/settings/rules/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsSlugRoute: typeof AssetsSlugRoute
  AssetsNewRoute: typeof AssetsNewRoute
  OnboardingExpensesRoute: typeof OnboardingExpensesRoute
  OnboardingIncomeRoute: typeof OnboardingIncomeRoute
  OnboardingPlanRoute: typeof OnboardingPlanRoute
  SettingsExpensesRoute: typeof SettingsExpensesRoute
  SettingsIncomeRoute: typeof SettingsIncomeRoute
  AssetsIndexRoute: typeof AssetsIndexRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SettingsRulesIdRoute: typeof SettingsRulesIdRoute
  SettingsRulesNewRoute: typeof SettingsRulesNewRoute
  SettingsRulesIndexRoute: typeof SettingsRulesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/': {
      id: '/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof AssetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/$slug': {
      id: '/assets/$slug'
      path: '/assets/$slug'
      fullPath: '/assets/$slug'
      preLoaderRoute: typeof AssetsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/new': {
      id: '/assets/new'
      path: '/assets/new'
      fullPath: '/assets/new'
      preLoaderRoute: typeof AssetsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/expenses': {
      id: '/onboarding/expenses'
      path: '/onboarding/expenses'
      fullPath: '/onboarding/expenses'
      preLoaderRoute: typeof OnboardingExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/income': {
      id: '/onboarding/income'
      path: '/onboarding/income'
      fullPath: '/onboarding/income'
      preLoaderRoute: typeof OnboardingIncomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/plan': {
      id: '/onboarding/plan'
      path: '/onboarding/plan'
      fullPath: '/onboarding/plan'
      preLoaderRoute: typeof OnboardingPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/expenses': {
      id: '/settings/expenses'
      path: '/settings/expenses'
      fullPath: '/settings/expenses'
      preLoaderRoute: typeof SettingsExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/income': {
      id: '/settings/income'
      path: '/settings/income'
      fullPath: '/settings/income'
      preLoaderRoute: typeof SettingsIncomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/rules/': {
      id: '/settings/rules/'
      path: '/settings/rules'
      fullPath: '/settings/rules/'
      preLoaderRoute: typeof SettingsRulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/rules/$id': {
      id: '/settings/rules/$id'
      path: '/settings/rules/$id'
      fullPath: '/settings/rules/$id'
      preLoaderRoute: typeof SettingsRulesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/rules/new': {
      id: '/settings/rules/new'
      path: '/settings/rules/new'
      fullPath: '/settings/rules/new'
      preLoaderRoute: typeof SettingsRulesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsSlugRoute: AssetsSlugRoute,
  AssetsNewRoute: AssetsNewRoute,
  OnboardingExpensesRoute: OnboardingExpensesRoute,
  OnboardingIncomeRoute: OnboardingIncomeRoute,
  OnboardingPlanRoute: OnboardingPlanRoute,
  SettingsExpensesRoute: SettingsExpensesRoute,
  SettingsIncomeRoute: SettingsIncomeRoute,
  AssetsIndexRoute: AssetsIndexRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsRulesIdRoute: SettingsRulesIdRoute,
  SettingsRulesNewRoute: SettingsRulesNewRoute,
  SettingsRulesIndexRoute: SettingsRulesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
